### ISSUE TITLE
Code Review For Kanban Board

### ISSUE THREAD

**Issue by David-Kasilia** [techEmprez/react-group-capstone-project#45]
## **To Highlight**
Link to Kanban Board Setup: https://github.com/techEmprez/react-group-capstone-project/projects/1
We are a Team of Two People:
@techEmprez 
@David-Kasilia

**Comment by smunozmo** [comment]
Hi @David-Kasilia @techEmprez, 👋 

## Highlights 👏 

- Kanban board is set up correctly, great! 🎉 
- Both team members have cards assigned, excellent! 😎 

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

# APPROVED! 💯  💯  💯 

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>


Cheers and Happy coding! 🤓 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
